name: CI-Build-linux-and-macos

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * 1"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install Linux dependencies with caching
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: runner.os == 'Linux'
      with:
          # put your list of apt packages here for the dependencies you need
          packages: catch2 libspdlog-dev
          version: 1.0

    - name: Install macOS dependencies with caching
      uses: tecolicom/actions-use-homebrew-tools@v1
      if: runner.os == 'macOS'
      with:
          # put your list of homebrew packages here for the dependencies you need
          tools: spdlog catch2

    - name: Build (Release)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'release'
        buildPreset: 'release'
        testPreset: 'release'

    - name: Build (Debug)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'debug'
        buildPreset: 'debug'
        testPreset: 'debug'